spring:
  application:
    name: demo
  datasource:
      url: jdbc:postgresql://localhost:5435/${POSTGRES_DB}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driverClassName: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: update
      open-in-view: true
